### PR TITLE
account for some rubocop cop naming changes

### PR DESCRIPTION
**Pull request by net1957**
after your request on PR #4 

@maxmeyer, please review

### CODE REVIEW

**Comment by maxmeyer** [comment]
@net1957 I released 3.0.0 to rubygems yesterday. Are your issues fixed? I'm interested in how you use the gem. Do you have a rails app distributing proxy.pac files?

**Comment by net1957** [comment]
Thanks for the release.

I use it in a rails application to check the result of a proxy script.
the corporate environment use many proxy. It help us to verify if it is working properly.

image

**Comment by maxmeyer** [comment]
That's great. I was thinking about building something similar. Is this rails app Open Source?

**Comment by net1957** [comment]
at this time it's not open source, but it should not be to difficult to do it.

**Comment by maxmeyer** [comment]
If this is not that much work why not releasing it to the public? :smile:

**Comment by net1957** [comment]
Hello!

it's done on https://github.com/net1957/ProxyCheck

@maxmeyer, I'm awaiting your feedback.
Regards

**Pull request merged**
